PROXIMITIES   x1 x2 x3 x4 x5 x6 x7
  /MATRIX OUT('C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\spss568\spssclus.tmp')
  /VIEW=VARIABLE
  /MEASURE=SEUCLID
  /PRINT NONE
  /STANDARDIZE=VARIABLE NONE.
 CLUSTER
  /MATRIX IN('C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\spss568\spssclus.tmp')
  /METHOD BAVERAGE
  /PRINT SCHEDULE
  /PLOT DENDROGRAM VICICLE.
 ERASE  FILE='C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\spss568\spssclus.tmp'.

  

 

 

